# Generated by Django 4.1.13 on 2025-07-21 10:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("images", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="image",
            old_name="useer",
            new_name="user",
        ),
    ]
