# Generated by Django 4.1.13 on 2025-07-28 12:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("account", "0002_contact_contact_account_con_created_8bdae6_idx"),
    ]

    operations = [
        migrations.AlterField(
            model_name="profile",
            name="photo",
            field=models.ImageField(blank=True, null=True, upload_to="users/%Y/%m/%d"),
        ),
    ]
