name: CI

on:
  push:
    branches: [master, dev]
  pull_request:
    branches: [master, dev]

jobs:
  test:

    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: "3.10"

    - name: Install Poetry
      uses: abatilo/actions-poetry@v2
      with:
        poetry-version: "2.1.3"

    - name: Install dependencies
      run: poetry install --no-root

    - name: Check code style with black
      run: poetry run black .

    - name: Check import order with isort
      run: poetry run isort .

    - name: Lint with flake8
      run: poetry run flake8